<a href="https://colab.research.google.com/github/Himan2580/Himanshu-Sharma/blob/master/Tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
import numpy as np

In [0]:
sess = tf.InteractiveSession()

In [0]:
from datetime import date
date.today()

datetime.date(2019, 7, 10)

## **Arithmetic Operators**

In [0]:
x_ = np.array([1,2,3])
y_ = np.array([-1,-2,-3])
x = tf.convert_to_tensor(x_)
y = tf.convert_to_tensor(y_)
output1 = tf.add(x, y)
print(output1.eval())
output2 = x + y
assert np.array_equal(output1.eval(),output2.eval())

[0 0 0]


In [0]:
x_ = np.array([3,4,5])
y_ = np.array(3)
x = tf.convert_to_tensor(x_)
y = tf.convert_to_tensor(y_)
output1 = tf.subtract(x,y)
output2 = x - y
print(output1.eval())
assert np.array_equal(output1.eval(),output2.eval())

[0 1 2]


In [0]:
x_ = np.array([4,5,6])
x = tf.convert_to_tensor(x_)
output1 = tf.scalar_mul(5,x)
output2 = x * 5
print(output1.eval())
assert np.array_equal(output1.eval(), output2.eval())

[20 25 30]


# **Matrix math function**

In [0]:
x_ = np.array([1,2,3,4])
x = tf.convert_to_tensor(x_)
output = tf.diag(x)
print(output.eval())

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [0]:
g = tf.Graph()
with g.as_default():
  with tf.name_scope("inputs"):
    a = tf.constant(2, tf.int32, name="a")
    b = tf.constant(3, tf.int32, name="b")
    
  with tf.name_scope("ops"):
    c = tf.multiply(a, b, name="c")
    d = tf.add(a, b, name="d")
    e = tf.subtract(c, d, name="e")
    
sess = tf.Session(graph=g)
c_,d_,e_ = sess.run([c,d,e])
print("c =", c_)
print("d =",d_)
print("e =",e_)

sess.close()

c = 6
d = 5
e = 1


In [0]:
# Define inputs
a = tf.Variable(tf.random_uniform([]))
b_pl = tf.placeholder(tf.float32, [None])

# Ops
c = a * b_pl
d = a + b_pl
e = tf.reduce_sum(c)
f = tf.reduce_mean(d)
g = e - f

# initialize variable(s)
init = tf.global_variables_initializer()

# Update variable
update_op = tf.assign(a, a + g)

In [0]:
writer = tf.summary.FileWriter('asset', tf.get_default_graph())

In [0]:
tf.summary.scalar("a", a)

<tf.Tensor 'a:0' shape=() dtype=string>

In [0]:
tf.summary.histogram("c", c)
tf.summary.histogram("d", d)

<tf.Tensor 'd:0' shape=() dtype=string>

In [0]:
summaries = tf.summary.merge_all()

In [0]:
sess = tf.Session()

In [0]:
sess.run(init)

In [0]:
for step in range(5):
    _b = np.arange(10, dtype=np.float32)
    _, summaries_proto = sess.run([update_op, summaries], {b_pl:_b})
    
    # Q8. Attach summaries_proto to TensorBoard.
    writer.add_summary(summaries_proto, global_step=step)
    
# Close the session
sess.close()

In [0]:
tf.reset_default_graph()

In [0]:
# Define inputs
a = tf.Variable(tf.random_uniform([]))
b_pl = tf.placeholder(tf.float32, [None])

# Ops
c = a * b_pl
d = a + b_pl
e = tf.reduce_sum(c)
f = tf.reduce_mean(d)
g = e - f

# initialize variable(s)
init = tf.global_variables_initializer()

# Update variable
update_op = tf.assign(a, a + g)

# Q4. Create a (summary) writer to `asset`
writer = tf.summary.FileWriter('asset', tf.get_default_graph())

#Q5. Add `a` to summary.scalar
tf.summary.scalar("a", a)

#Q6. Add `c` and `d` to summary.histogram
tf.summary.histogram("c", c)
tf.summary.histogram("d", d)

#Q7. Merge all summaries.
summaries = tf.summary.merge_all()

# Start a session
sess = tf.Session()

# Initialize Variable(s)
sess.run(init)

# Fetch the value of c, d, and e.
for step in range(5):
    _b = np.arange(10, dtype=np.float32)
    _, summaries_proto = sess.run([update_op, summaries], {b_pl:_b})
    
    # Q8. Attach summaries_proto to TensorBoard.
    writer.add_summary(summaries_proto, global_step=step)
    
# Close the session
sess.close()

In [0]:
#Create a graph
g = tf.Graph()

with g.as_default():
    with tf.name_scope("inputs"):
        a = tf.constant(2, tf.int32, name="a")
        b = tf.constant(3, tf.int32, name="b")

    with tf.name_scope("ops"):
        c = tf.multiply(a, b, name="c")
        d = tf.add(a, b, name="d")
        e = tf.subtract(c, d, name="e")

#Start a session
sess = tf.Session(graph=g)

#Fetch c, d, e
c_, d_, e_ = sess.run([c, d, e])
print("c =", c_)
print("d =", d_)
print("e =", e_)

sess.close()

c = 6
d = 5
e = 1


In [0]:
tf.reset_default_graph()

In [0]:
output = tf.constant([[1,3,5],[4,6,8]], dtype = tf.float32)
print(output.eval())
assert np.allclose(output.eval(), np.array([[1,3,5],[4,6,8]], dtype = np.float32))


[[1. 3. 5.]
 [4. 6. 8.]]


In [0]:
##Here we are creating a random tensors of the 3 x 2 with elements from  normal distribution of mean=0 and standard deviation=2
x = tf.random_normal([3, 2],0, 2.)
print(x.eval())

[[ 1.1118735  1.2449933]
 [-1.5471766  4.409965 ]
 [-0.2753615  2.365573 ]]


In [0]:
##Create a random tensor of the shape [3, 2], with elements from a normal distribution of mean=0, standard deviation=1 
#such that any values don't exceed 2 standard deviations from the mean.
output = tf.truncated_normal([3, 2])
print(output.eval())

[[-1.3163658  -0.6023648 ]
 [-1.37537    -0.21423396]
 [ 0.0919451  -1.220524  ]]


### Variables


In [0]:
x = tf.Variable(1.0, name="weight")
with tf.Session() as sess:
    sess.run(x.initializer)
    print(sess.run(x))

1.0


In [0]:
x1 = tf.Variable(1.0)
x2 = tf.Variable(2.0)
x3 = tf.Variable(3.0)

output = x1 + x2 + x3

# Q. Add an Op to initialize global variables.
init_op = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init_op) # Initialize all variables.
    print(sess.run(out))

6.0


In [0]:
import tensorflow as tf
const = tf.constant(2.0, name="const")
    
x = tf.Variable(2.0, name='x')  ## create TensorFlow variables
y = tf.Variable(1.0, name='y')

In [0]:
# now create some operations
d = tf.add(x, y, name='d')
e = tf.add(y, const, name='e')
a = tf.multiply(d, e, name='a')

In [0]:
init_op = tf.global_variables_initializer()

In [0]:
# start the session
with tf.Session() as sess:
    sess.run(init_op)
    # compute the output of the graph
    a_out = sess.run(a)
    print("Variable a is {}".format(a_out))

Variable a is 9.0
